/***************************************************************************************
* \file Smart_Lights_Demo_U55_CMDmodel.h
****************************************************************************************
* NOTE: This file is auto-generated by web tool. Please do not edit this file manually.
* \copyright
* Copyright 2025, Infineon Technologies.
* All rights reserved.
****************************************************************************************/

#ifndef SMART_LIGHTS_DEMO_U55_CMDMODEL_H
#define SMART_LIGHTS_DEMO_U55_CMDMODEL_H

extern const char Smart_Lights_Demo_CMDmodeldata[];
#define SMART_LIGHTS_DEMO_CMDMODELDATA_SIZE 42536

#endif // SMART_LIGHTS_DEMO_U55_CMDMODEL_H
