/***************************************************************************************
* \file Smart_Lights_Demo_U55_WWmodel.h
****************************************************************************************
* NOTE: This file is auto-generated by web tool. Please do not edit this file manually.
* \copyright
* Copyright 2025, Infineon Technologies.
* All rights reserved.
****************************************************************************************/

#ifndef SMART_LIGHTS_DEMO_U55_WWMODEL_H
#define SMART_LIGHTS_DEMO_U55_WWMODEL_H

extern const char Smart_Lights_Demo_WWmodeldata[];
#define SMART_LIGHTS_DEMO_WWMODELDATA_SIZE 7448

#endif // SMART_LIGHTS_DEMO_U55_WWMODEL_H
