/***************************************************************************************
* \file LED_Demo_U55_CMDmodel.h
****************************************************************************************
* NOTE: This file is auto-generated by web tool. Please do not edit this file manually.
* \copyright
* Copyright 2025, Infineon Technologies.
* All rights reserved.
****************************************************************************************/

#ifndef LED_DEMO_U55_CMDMODEL_H
#define LED_DEMO_U55_CMDMODEL_H

extern const char LED_Demo_CMDmodeldata[];
#define LED_DEMO_CMDMODELDATA_SIZE 5924

#endif // LED_DEMO_U55_CMDMODEL_H
