/***************************************************************************************
* \file LED_Demo_U55_WWmodel.h
****************************************************************************************
* NOTE: This file is auto-generated by web tool. Please do not edit this file manually.
* \copyright
* Copyright 2025, Infineon Technologies.
* All rights reserved.
****************************************************************************************/

#ifndef LED_DEMO_U55_WWMODEL_H
#define LED_DEMO_U55_WWMODEL_H

extern const char LED_Demo_WWmodeldata[];
#define LED_DEMO_WWMODELDATA_SIZE 7448

#endif // LED_DEMO_U55_WWMODEL_H
