/***************************************************************************************
* \file Cooktop_Demo_U55_WWmodel.h
****************************************************************************************
* NOTE: This file is auto-generated by web tool. Please do not edit this file manually.
* \copyright
* Copyright 2025, Infineon Technologies.
* All rights reserved.
****************************************************************************************/

#ifndef COOKTOP_DEMO_U55_WWMODEL_H
#define COOKTOP_DEMO_U55_WWMODEL_H

extern const char Cooktop_Demo_WWmodeldata[];
#define COOKTOP_DEMO_WWMODELDATA_SIZE 7396

#endif // COOKTOP_DEMO_U55_WWMODEL_H
