/***************************************************************************************
* \file Cooktop_Demo_U55_CMDmodel.h
****************************************************************************************
* NOTE: This file is auto-generated by web tool. Please do not edit this file manually.
* \copyright
* Copyright 2025, Infineon Technologies.
* All rights reserved.
****************************************************************************************/

#ifndef COOKTOP_DEMO_U55_CMDMODEL_H
#define COOKTOP_DEMO_U55_CMDMODEL_H

extern const char Cooktop_Demo_CMDmodeldata[];
#define COOKTOP_DEMO_CMDMODELDATA_SIZE 4964

#endif // COOKTOP_DEMO_U55_CMDMODEL_H
