/***************************************************************************************
* \file Coffee.h
****************************************************************************************
* NOTE: This file is auto-generated by web tool. Please do not edit this file manually.
* \copyright
* Copyright 2025, Infineon Technologies.
* All rights reserved.
****************************************************************************************/

#ifndef COFFEE_H
#define COFFEE_H

#include <stdint.h>

#define COFFEE_NUM_INTENTS 12
#define COFFEE_NUM_COMMANDS 99
#define COFFEE_NUM_VARIABLES 7
#define COFFEE_NUM_VARIABLE_PHRASES 25
#define COFFEE_NUM_UNIT_PHRASES 16
#define COFFEE_INTENT_MAP_ARRAY_TOTAL_SIZE 374
#define COFFEE_UNIT_PHRASE_MAP_ARRAY_TOTAL_SIZE 105

extern const char* Coffee_intent_name_list[COFFEE_NUM_INTENTS];

extern const char* Coffee_variable_name_list[COFFEE_NUM_VARIABLES];

extern const char* Coffee_variable_phrase_list[COFFEE_NUM_VARIABLE_PHRASES];

extern const char* Coffee_unit_phrase_list[COFFEE_NUM_UNIT_PHRASES];

extern const int Coffee_intent_map_array[COFFEE_INTENT_MAP_ARRAY_TOTAL_SIZE];

extern const int Coffee_intent_map_array_sizes[COFFEE_NUM_COMMANDS];

extern const int Coffee_variable_phrase_sizes[COFFEE_NUM_VARIABLES];

extern const int Coffee_unit_phrase_map_array[COFFEE_UNIT_PHRASE_MAP_ARRAY_TOTAL_SIZE];

extern const int Coffee_unit_phrase_map_array_sizes[COFFEE_NUM_COMMANDS];

#endif // COFFEE_H
