/***************************************************************************************
* \file Coffee_U55_CMDmodel.h
****************************************************************************************
* NOTE: This file is auto-generated by web tool. Please do not edit this file manually.
* \copyright
* Copyright 2025, Infineon Technologies.
* All rights reserved.
****************************************************************************************/

#ifndef COFFEE_U55_CMDMODEL_H
#define COFFEE_U55_CMDMODEL_H

extern const char Coffee_CMDmodeldata[];
#define COFFEE_CMDMODELDATA_SIZE 45100

#endif // COFFEE_U55_CMDMODEL_H
