/***************************************************************************************
* \file Coffee_U55_WWmodel.h
****************************************************************************************
* NOTE: This file is auto-generated by web tool. Please do not edit this file manually.
* \copyright
* Copyright 2025, Infineon Technologies.
* All rights reserved.
****************************************************************************************/

#ifndef COFFEE_U55_WWMODEL_H
#define COFFEE_U55_WWMODEL_H

extern const char Coffee_WWmodeldata[];
#define COFFEE_WWMODELDATA_SIZE 7372

#endif // COFFEE_U55_WWMODEL_H
